### PR TITLE
For Wagtail 1.7+, we need to append to a list instead of a tuple

### PR DESCRIPTION
**Pull request by helmantel**
Hi infoportugal, 

I added a minor change to _patch_elasticsearch_fields which allows us to use Wagtail version 1.7+. Could you please integrate this minor change into the master branch?

Cheers,
Wietze.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
I think that the better update have to be based in original package, and make soon!

**Comment by benjaoming** [comment]
wagtail-modeltranslation is definitely broken in current Wagtail 1.7

@helmantel could you rebase against `master` to make tests run?

**Comment by helmantel** [comment]
Fork was rebased against master!

**Comment by Alexandre27** [comment]
Thanks @helmantel. Your code was added in the refactor for version 0.6.

**Pull request closed without merging**
