### PR TITLE
Add Migrate command

### LINKED ISSUE #175: Translated fields not created in test database
When I run my (previously working) Django unit tests, I get the following traceback

```Python traceback
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "/project/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/project/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: wagtailcore_page.title_nl

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/pycharm-2017.2.1/helpers/pycharm/django_test_manage.py", line 168, in <module>
    utility.execute()
  File "/pycharm-2017.2.1/helpers/pycharm/django_test_manage.py", line 142, in execute
    _create_command().run_from_argv(self.argv)
  File "/project/lib/python3.5/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/project/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/project/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/joren/Software/pycharm-2017.2.1/helpers/pycharm/django_test_manage.py", line 104, in handle
    failures = TestRunner(test_labels, **options)
  File "/home/joren/Software/pycharm-2017.2.1/helpers/pycharm/django_test_runner.py", line 255, in run_tests
    extra_tests=extra_tests, **options)
  File "/home/joren/Software/pycharm-2017.2.1/helpers/pycharm/django_test_runner.py", line 156, in run_tests
    return super(DjangoTeamcityTestRunner, self).run_tests(test_labels, extra_tests, **kwargs)
  File "/project/lib/python3.5/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/project/lib/python3.5/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/project/lib/python3.5/site-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/project/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 77, in create_test_db
    self.connection._test_serialized_contents = self.serialize_db_to_string()
  File "/project/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 121, in serialize_db_to_string
    serializers.serialize("json", get_objects(), indent=None, stream=out)
  File "/project/lib/python3.5/site-packages/django/core/serializers/__init__.py", line 129, in serialize
    s.serialize(queryset, **options)
  File "/project/lib/python3.5/site-packages/django/core/serializers/base.py", line 80, in serialize
    for count, obj in enumerate(queryset, start=1):
  File "/project/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 117, in get_objects
    for obj in queryset.iterator():
  File "/project/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/project/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/project/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/project/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/project/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/project/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/project/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/project/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: wagtailcore_page.title_nl

Process finished with exit code 1
```

### PR DESCRIPTION
**Pull request by dmarcelino**
Fixes #175.

This PR adds a new `migrate` command which overrides Django's own `migrate` to additionally run `sync_page_translation_fields` and silence any missing wagtailcore migrations warnings. Docs included.

As seen in #175 this is useful in testing where `sync_page_translation_fields` needs to be run after `migrate`.

---
**Edit**: there's a good discussion about this approach on #175, which is worth reading. The following paragraph is taken from there but it's relevant to state it here:

> initially I was against adding a `migrate` command override but ended up doing it. I still think people should generally avoid it (so they know what's happening) but it's certainly the simpler solution for running tests.

### CODE REVIEW

**Comment by dmarcelino** [comment]
Olá @DiogoMarques29 and @Alexandre27, let me know if you have any concerns with this PR.

**Comment by DiogoMarques29** [comment]
Olá @dmarcelino 
Sounds good to me. This gives the user the option to choose either to add the `migrate` app to installed apps and thus automatically sync the database schema or run the command manually.

What do you think @Alexandre27 ?
Cheers

**Comment by Alexandre27** [comment]
Olá @dmarcelino e @DiogoMarques29 
I only have one concern about this PR, and it has to do with CD tools because if i recall correctly the `sync_page_translation_fields` doesn't have a `--no-input` option so it won't work with most automation tools.
Other than that, it looks good.

**Comment by dmarcelino** [comment]
@Alexandre27, our [sync_page_translation_fields](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/management/commands/sync_page_translation_fields.py) is essentially a wrapper for django-modeltranslation's `sync_translation_fields` which limits the scope to `Page`. `sync_translation_fields` supports `--noinput` (see [sync_translation_fields.py#L62](https://github.com/deschler/django-modeltranslation/blob/master/modeltranslation/management/commands/sync_translation_fields.py#L62)) and so does `sync_page_translation_fields`.

Also we've been running `sync_page_translation_fields` silently, even though programmatically, in the test suite for some time: [wagtail_modeltranslation/tests/tests.py#L105](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/tests/tests.py#L105).

Cheers

**Comment by dmarcelino** [comment]
Bom dia @Alexandre27, any update on this?

**Comment by DiogoMarques29** [comment]
Boa tarde @dmarcelino 

I've been talking with @Alexandre27 and that was our only concern about this PR. The rest seems good. Merging!

**Comment by dmarcelino** [comment]
Good stuff!

**Pull request merged**
