### PR TITLE
Fix #318 ImportError after wagtail update to 2.11

### LINKED ISSUE #318: Wagtail 2.11 compatibility
I recently updated the new version of Wagtail 2.11, and I get the following error.

` File "/Users/mario/Documents/GitHub/environments/ve_wagtail/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/mario/Documents/GitHub/environments/ve_wagtail/lib/python3.7/site-packages/wagtail_modeltranslation/wagtail_hooks.py", line 29, in <module>
    from wagtail.wagtailcore import hooks
ModuleNotFoundError: No module named 'wagtail.wagtailcore'`

I think it is related to this function
`from wagtail.admin.views.pages import get_valid_next_url_from_request
` does not exist in the new version of wagtail

Is an update planned to solve these problems?

### PR DESCRIPTION
**Pull request by tissieres**
Hello,
This one was easy to fix.
Cheers
Cedric

### CODE REVIEW

**Comment by DiogoMarques29** [comment]
Hello! Thanks for the PR.
However, this PR would break projects using wagtail < 2.11, can you add a validation to use this import only for wagtail >= 2.11?
Cheers

**Comment by tissieres** [comment]
Hello, thanks for your review. 
Would it be fine like this? I did not sort the import since I don't know that your policy about this is. 
Cedric

**Comment by perepicornell** [comment]
Thanks for taking care of this, I downgraded Wagail to 2.10.2 while the fix is not merged. Maybe this issue is critical enough as for warning about it at the documentation until it gets fixed?

**Comment by DiogoMarques29** [comment]
Sorry for the time waiting. Merged

**Pull request merged**
