### PR TITLE
_get_site_root_paths: clear cache when changing languages

### LINKED ISSUE #195: Translating root_page.slug breaks child_page.url when changing language
See https://github.com/infoportugal/wagtail-modeltranslation/issues/195#issuecomment-376732049 for a detailed explanation of the issue and see https://github.com/dmarcelino/wagtail-modeltranslation/commit/5648c0b16412cb54cb7b780824b63d410245d8b9 for a failing test.

For now the workaround is to not translate a root page slug.

Edited by @dmarcelino

---

Hi all,

This is another new issue that didn't exist in 0.6, but when accessing a `Page` objects `url` property, translation seems to fail.

For example, in a shell:
```
from django.utils import translation
translation.activate('en')
for p in Page.objects.all():
    p.url
    p.slug

translation.activate('fr')
for p in Page.objects.all():
    p.url
    p.slug
```

In the above example, the `url` property will print just fine on the first run, but once the language changes `url` property is blank - although the `slug` property returns the correct value based on the activated language.

This wasn't an issue in 0.6.

Any thoughts?

EDIT: This seems to also cause `change_lang` to return None (similar to Issue #13)

### PR DESCRIPTION
**Pull request by dmarcelino**
Fixes #195

In https://github.com/infoportugal/wagtail-modeltranslation/issues/195#issuecomment-376732049 @dwasyl has uncovered that `Site.get_site_root_paths()` returns a cached copy of site root paths which can be of the wrong language causing `Page.url` to return `None`.

Changes in this PR:

- Change `PageFactory.create_page_tree()` to return a page structure that better mimics Wagtail's live behaviour
- Failing test
- ~~Decorator to clear the cached sites if the language changed.~~
- Monkey patches `Page._get_site_root_paths()` so it returns site root paths for the current language
- For Wagtail<1.11 monkey patch `Page.get_url_parts()` with the most recent code which calls `Page._get_site_root_paths()`

### CODE REVIEW

**Comment by dmarcelino** [comment]
@dwasyl, @francois-travais and @agelinas, can you please try this fix on your test setups? You can install it with `pip install -e git+https://github.com/dmarcelino/wagtail-modeltranslation.git@2621e6e4078d42d7a8491b2fe4d046e67ccebe97#egg=wagtail-modeltranslation`

Thanks!

**Comment by francois-travais** [comment]
It doesn't work for me neither. I debugged it and for some reason `cache_object._wagtail_cached_site_root_paths_language` and `cache_object._wagtail_cached_site_root_paths` are not present in `cache_object` in the wrapper scope while they are present in the actual `Page._get_site_root_paths` method. Therefore the wrapper doesn't do anything when the language changes. In my case `cache_object` is `self`, a wagtail page.

**Comment by dmarcelino** [comment]
Thanks @francois-travais, your debug report allowed me to find what I believe to be the root issue. There are 2 different caching levels, the `Page`/`Request`'s `cache_object` and the `Site`'s `'wagtail_site_root_paths'`. This last one could become stale when new requests of differing language hit the Wagtail `Page`. In light of this `test_root_page_slug` has been expanded to hit this scenario.

I've addressed the issue with a different approach from before: a site_root_paths cache per language. This results in less cache evictions and a more robust handling. It does however require deeper monkey patching but I see  little or no alternative to that.

Please test this last commit:

```
pip install -e git+https://github.com/dmarcelino/wagtail-modeltranslation.git@a92cf200a3880e95b70f2a6a0a785339a8e4ac27#egg=wagtail-modeltranslation
```

**Comment by francois-travais** [comment]
This version works for me! Well done @dmarcelino

**Comment by dmarcelino** [comment]
Nice, It's good to hear that @francois-travais.

**Comment by dmarcelino** [comment]
Bom dia @DiogoMarques29 and @Alexandre27! Please review this PR which has been successfully tested by @francois-travais, @agelinas and @dwasyl.

Cheers!

**Comment by DiogoMarques29** [comment]
Bom dia @dmarcelino 

Looks good. Merging!

Cheers

**Comment by dmarcelino** [comment]
Thanks @DiogoMarques29!

**Pull request merged**
