### PR TITLE
Fix inherited fields when using django-modeltranslation >= 0.19

### LINKED ISSUE #429: Inherited fields are not pached when using django-modeltranslation > 0.19.0
Fields like `title` and `slug` are not being patched in wagtail admin page due to django-modeltranslation splitting the `fields` attribute into `local_fields` and `all_fields`.

I've been able to fix this by replacing all instances of `translator.get_options_for_model(...).fields` into `translator.get_options_for_model(...).all_fields`

### PR DESCRIPTION
**Pull request by tognee**
Fixes and closes #429

### CODE REVIEW

**Comment by DiogoMarques29** [comment]
Hi @tognee,

Could you please update this line in the workflow? https://github.com/infoportugal/wagtail-modeltranslation/blob/21fa6f9098c42d658287f27432af62dfdb404085/.github/workflows/python-package.yml#L40

The tests should now use version 0.19 of django-modeltranslation.

Thank you!

**Comment by jorenham** [comment]
ping @tognee

**Comment by tognee** [comment]
Sorry, totally forgot about this PR. I've changed the version in the CI and made a new commit

**Comment by jorenham** [comment]
@DiogoMarques29 Would you mind taking another look?

**Comment by jgeskens** [comment]
@dirkmoors

**Comment by tognee** [comment]
@DiogoMarques29 Any news on when this will be merged?

**Comment by delzotto** [comment]
No news about this PR?
It's very important

**Pull request merged**
