### PR TITLE
Add WAGTAILMODELTRANSLATION_LOCALE_PICKER_DEFAULT

### LINKED ISSUE #287: Toggle all languages on default editing
Hi,

I'm trying to enable editing on all languages by default, like this : https://www.screencast.com/t/hNOKRyIuF30J

I was able, when manually editing language_toggles.js : https://www.screencast.com/t/wRedUnAbF

Is there any other (clean) way to achieve this ?

Thanks,

### PR DESCRIPTION
**Pull request by buczek**
Make the set of languages, which are initially enabled on the edit pages
when WAGTAILMODELTRANSLATION_LOCALE_PICKER is used, configurable:

    WAGTAILMODELTRANSLATION_LOCALE_PICKER_DEFAULT = None

This is the default, only the default languge will initially be enabled.

    WAGTAILMODELTRANSLATION_LOCALE_PICKER_DEFAULT = []

No languages are initially disabled.

    WAGTAILMODELTRANSLATION_LOCALE_PICKER_DEFAULT = ['en', 'de']

The given set of languages are enabled.

Resolves #287

### CODE REVIEW

**Comment by buczek** [comment]
WAGTAILMODELTRANSLATION_LOCALE_PICKER_DEFAULT = ( ) 
WAGTAILMODELTRANSLATION_LOCALE_PICKER_DEFAULT = ( 'en', )
WAGTAILMODELTRANSLATION_LOCALE_PICKER_DEFAULT = ( 'en', 'de' ) 

also work as expected. But aside from the commit message, documentation is missing anyway. Is the setting name to long?

**Comment by DiogoMarques29** [comment]
Hello @buczek 
Thanks for the PR, looks good.

Could you also add documentation [here](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/docs/advanced%20settings.rst)

Cheers

**Comment by buczek** [comment]
Will do,

**Comment by buczek** [comment]
Please double check. I don't even know how to build the documentation to verify how it looks. Any maybe you don't like the style with the commented variants?

**Comment by DiogoMarques29** [comment]
Thanks for the PR! Merged!

**Pull request merged**
